version: '3.9'
name: docker-workshop-stack
services:
  nodejs:
    container_name: node-js-app-container_name
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev 
    ports:
      - '3001:3000'
    volumes:
     - .:/my-app
    depends_on:
      - mongodb
    networks:
     - nodejs-network 
  mongodb:
    container_name: mongodb 
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
     - '5000:27017'
    volumes:
     - mongodb-volume: /data/db
    networks:
     - nodejs-network

networks:
  nodejs-network:
   driver: bridge
  telecom:
   driver: bridge

volumes:
  mongodb-volume:
